// Minimal ABI for the Coercion-Resistant Vault — only the methods the demo uses.
// Generated by hand from src/CoercionResistantVault.sol to avoid pulling in
// the full Foundry build output (out/CoercionResistantVault.sol/CoercionResistantVault.json).
//
// If you add new vault methods you want to call from the frontend, append
// their ABI fragments here.

export const VAULT_ABI = [
  // --- Views ---
  "function owner() view returns (address)",
  "function totalBalance() view returns (uint256)",
  "function hotBalance() view returns (uint256)",
  "function coldBalance() view returns (uint256)",
  "function remainingHotBudget() view returns (uint256)",
  "function spendingLimit() view returns (uint256)",
  "function epochDuration() view returns (uint256)",
  "function spentInCurrentEpoch() view returns (uint256)",
  "function timelockDuration() view returns (uint256)",
  "function multisigThreshold() view returns (uint256)",
  "function guardianCount() view returns (uint256)",
  "function isGuardian(address) view returns (bool)",
  "function isWhitelisted(address) view returns (bool)",
  "function isPaused() view returns (bool)",
  "function pausedUntil() view returns (uint256)",
  "function pendingWithdrawalCount() view returns (uint256)",
  "function nextRequestId() view returns (uint256)",
  "function getWithdrawalRequest(uint256) view returns (address token, address to, uint256 amount, uint256 unlockTime, bool executed, bool cancelled, uint256 approvalCount)",

  // --- Owner actions ---
  "function deposit() payable",
  "function hotSpend(address payable to, uint256 amount)",
  "function requestWithdrawal(address payable to, uint256 amount) returns (uint256 requestId)",
  "function executeWithdrawal(uint256 requestId)",
  "function cancelWithdrawal(uint256 requestId)",
  "function setWhitelistedTarget(address target, bool allowed)",
  "function executeWhitelistChange(address target)",
  "function approveToken(address token, address spender, uint256 amount)",
  "function execute(address target, uint256 value, bytes data) returns (bytes)",

  // --- Guardian actions ---
  "function approveWithdrawal(uint256 requestId)",
  "function pause()",
  "function unpause()",

  // --- Events (for log display) ---
  "event Deposited(address indexed sender, uint256 amount)",
  "event HotSpend(address indexed to, uint256 amount)",
  "event WithdrawalRequested(uint256 indexed requestId, address indexed token, address indexed to, uint256 amount, uint256 unlockTime)",
  "event WithdrawalExecuted(uint256 indexed requestId)",
  "event WithdrawalCancelled(uint256 indexed requestId, address cancelledBy)",
  "event WithdrawalApprovedByMultisig(uint256 indexed requestId)",
  "event TargetWhitelisted(address indexed target, bool allowed)",
  "event WhitelistChangeScheduled(address indexed target, uint256 effectiveTime)",
  "event TokenApproval(address indexed token, address indexed spender, uint256 amount)",
  "event Executed(address indexed target, uint256 value, bytes data, bytes result)",
  "event VaultPaused(address indexed by, uint256 until)",
  "event VaultUnpaused(address indexed by)"
];

export const WETH_ABI = [
  "function deposit() payable",
  "function withdraw(uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function approve(address, uint256) returns (bool)",
  "function transfer(address, uint256) returns (bool)"
];

export const ERC20_ABI = [
  "function balanceOf(address) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
  "function transfer(address, uint256) returns (bool)"
];

export const UNISWAP_ROUTER_ABI = [
  "function exactInputSingle((address tokenIn, address tokenOut, uint24 fee, address recipient, uint256 amountIn, uint256 amountOutMinimum, uint160 sqrtPriceLimitX96) params) payable returns (uint256 amountOut)"
];
